/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/index 2` | `/index 2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/bubble-tap`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/cloud`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/manual`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/paste`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/photo`; params?: Router.UnknownInputParams; } | { pathname: `/bubble/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/index 2` | `/index 2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/add-contact/bubble-tap`; params?: Router.UnknownOutputParams; } | { pathname: `/add-contact/cloud`; params?: Router.UnknownOutputParams; } | { pathname: `/add-contact`; params?: Router.UnknownOutputParams; } | { pathname: `/add-contact/manual`; params?: Router.UnknownOutputParams; } | { pathname: `/add-contact/paste`; params?: Router.UnknownOutputParams; } | { pathname: `/add-contact/photo`; params?: Router.UnknownOutputParams; } | { pathname: `/bubble/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/contact/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/index 2${`?${string}` | `#${string}` | ''}` | `/index 2${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/add-contact/bubble-tap${`?${string}` | `#${string}` | ''}` | `/add-contact/cloud${`?${string}` | `#${string}` | ''}` | `/add-contact${`?${string}` | `#${string}` | ''}` | `/add-contact/manual${`?${string}` | `#${string}` | ''}` | `/add-contact/paste${`?${string}` | `#${string}` | ''}` | `/add-contact/photo${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/index 2` | `/index 2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/bubble-tap`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/cloud`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/manual`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/paste`; params?: Router.UnknownInputParams; } | { pathname: `/add-contact/photo`; params?: Router.UnknownInputParams; } | `/bubble/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/contact/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/bubble/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/contact/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
